import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeInstagram,normalizeKoreanPhone,validateStart} from '../server-reference/validation.mjs';
import {tokenRefreshDecision,expiryFromResponse} from '../server-reference/token-policy.mjs';
import {buildNotification,escapeHtml} from '../server-reference/notification.mjs';
const base=()=>({requestKey:'b1c9a751-283b-4e88-97cc-8229c74059d4',policyBundleId:'test-approved-bundle',fullName:'김셀럽',email:'creator@example.com',phone:'010-0000-0000',instagramUsername:'@Celeblife_demo',consents:{age:true,terms:true,privacy:true,instagramData:true}});
const validate=x=>validateStart(x,'test-approved-bundle');
test('valid form normalizes values without inferring ownership',()=>{const r=validate(base());assert.equal(r.ok,true);assert.equal(r.value.phone,'+821000000000');assert.equal(r.value.instagramUsername,'celeblife_demo');assert.equal(r.value.email,'creator@example.com');});
test('blank name is rejected',()=>{const r=validate({...base(),fullName:' '});assert.equal(r.ok,false);assert.ok(r.errors.fullName);});
test('single character names are not arbitrarily excluded',()=>assert.equal(validate({...base(),fullName:'K'}).ok,true));
test('name length is bounded',()=>assert.equal(validate({...base(),fullName:'a'.repeat(51)}).ok,false));
test('control characters in name are rejected',()=>assert.equal(validate({...base(),fullName:'a\nb'}).ok,false));
test('email requires syntax, not a claimed delivery check',()=>assert.equal(validate({...base(),email:'no-at'}).ok,false));
test('CRLF in email is rejected',()=>assert.equal(validate({...base(),email:'a@b.com\r\nBcc:x@y.com'}).ok,false));
test('unknown extra fields are dropped',()=>assert.equal('accessToken' in validate({...base(),accessToken:'never-carry-this'}).value,false));
test('all consents must be actual booleans',()=>assert.equal(validate({...base(),consents:{...base().consents,privacy:'true'}}).ok,false));
test('missing consent fails',()=>assert.equal(validate({...base(),consents:{}}).ok,false));
test('mismatched policy fails',()=>assert.equal(validate({...base(),policyBundleId:'old'}).ok,false));
test('no configured policy cannot silently proceed',()=>assert.throws(()=>validateStart(base(),''),/SERVER_POLICY/));
test('invalid request key fails',()=>assert.equal(validate({...base(),requestKey:'foo'}).ok,false));
test('non-object payload fails',()=>assert.equal(validate(null).ok,false));
test('IG normalization strips @ and lowercases',()=>assert.equal(normalizeInstagram(' @HeLLo_1 '),'hello_1'));
test('IG URL is not a username',()=>assert.equal(validate({...base(),instagramUsername:'https://instagram.com/demo'}).ok,false));
test('IG exceeds 30 characters',()=>assert.equal(validate({...base(),instagramUsername:'a'.repeat(31)}).ok,false));
test('phone letters are not silently discarded',()=>assert.equal(normalizeKoreanPhone('010-1234-5678abc'),null));
test('already international KR phone accepted',()=>assert.equal(normalizeKoreanPhone('+82 10 1234 5678'),'+821012345678'));
test('landline normalization',()=>assert.equal(normalizeKoreanPhone('02-123-4567'),'+8221234567'));
const now='2026-09-10T00:00:00.000Z';
const t={savedAt:'2026-09-01T00:00:00.000Z',expiresAt:'2026-09-12T00:00:00.000Z',now};
test('due token refreshes',()=>assert.equal(tokenRefreshDecision(t),'refresh'));
test('expired token requires reconnect',()=>assert.equal(tokenRefreshDecision({...t,expiresAt:now}),'reauth_required'));
test('fresh token is skipped',()=>assert.equal(tokenRefreshDecision({...t,savedAt:'2026-09-09T23:00:00.000Z'}),'too_new'));
test('exactly 24h old is eligible',()=>assert.equal(tokenRefreshDecision({...t,savedAt:'2026-09-09T00:00:00.000Z'}),'refresh'));
test('exactly 7 days remaining is not due, matching legacy strict cutoff',()=>assert.equal(tokenRefreshDecision({...t,expiresAt:'2026-09-17T00:00:00.000Z'}),'not_due'));
test('missing expiry does not invent 60 days',()=>assert.equal(tokenRefreshDecision({...t,expiresAt:null}),'metadata_missing'));
test('future save timestamp treated as bad metadata',()=>assert.equal(tokenRefreshDecision({...t,savedAt:'2026-09-11T00:00:00.000Z'}),'metadata_missing'));
test('timezone-free metadata rejected',()=>assert.equal(tokenRefreshDecision({...t,savedAt:'2026-09-01T00:00:00'}),'metadata_missing'));
test('actual expires_in determines expiry',()=>assert.equal(expiryFromResponse({access_token:'fixture-token',expires_in:3600},now),'2026-09-10T01:00:00.000Z'));
for(const expires_in of [undefined,0,-1,true,'3600',NaN,1.5]) test(`invalid expires_in ${String(expires_in)}`,()=>assert.throws(()=>expiryFromResponse({access_token:'fixture',expires_in},now),/INVALID_TOKEN_RESPONSE/));
test('token response requires a token',()=>assert.throws(()=>expiryFromResponse({expires_in:3600},now),/INVALID_TOKEN_RESPONSE/));
const notification=()=>({requestId:base().requestKey,fullName:'김셀럽',email:'creator@example.com',phone:'+821000000000',instagramUsername:'celeblife_demo',receivedAt:now});
test('mail deterministic key is receipt-specific',()=>{const r=buildNotification(notification());assert.equal(r.eventKey,`creator.connected:${base().requestKey}`);assert.match(r.text,/KST/);});
test('reconnection subject is distinct',()=>assert.match(buildNotification({...notification(),isReconnection:true}).subject,/재연동/));
test('HTML in name is escaped',()=>assert.ok(buildNotification({...notification(),fullName:'<b>셀럽</b>'}).html.includes('&lt;b&gt;')));
test('injected subject field rejected',()=>assert.throws(()=>buildNotification({...notification(),instagramUsername:'demo\r\nBcc:abc'}),/INVALID_NOTIFICATION/));
test('token is never included, even if caller supplies it',()=>assert.ok(!JSON.stringify(buildNotification({...notification(),accessToken:'TOP_SECRET'})).includes('TOP_SECRET')));
test('mail escaping includes quotes',()=>assert.equal(escapeHtml(`"'&<>`),'&quot;&#39;&amp;&lt;&gt;'));

test('replaceAttemptId is optional and explicitly preserved',()=>{const id=base().requestKey.toUpperCase();const r=validate({...base(),replaceAttemptId:id});assert.equal(r.ok,true);assert.equal(r.value.replaceAttemptId,id.toLowerCase());});
test('malformed replaceAttemptId is rejected',()=>assert.equal(validate({...base(),replaceAttemptId:'other'}).ok,false));
test('omitted replaceAttemptId is not invented',()=>assert.equal('replaceAttemptId' in validate(base()).value,false));
