import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeKoreanPhone,validateStart} from '../server-reference/validation.mjs';
import {startReplayDecision,confirmationMatches,canReplaceAttempt,shouldAcceptStatus,isOlderAttempt} from '../server-reference/attempt-policy.mjs';
const a='b1c9a751-283b-4e88-97cc-8229c74059d4',b='d071f1c9-f9db-498f-90c2-d8211ec26a99';
const t={payloadHash:'a'.repeat(64),storedPayloadHash:'a'.repeat(64),status:'pending',stateExpiresAt:'2026-09-10T00:10:00Z',now:'2026-09-10T00:00:00Z'};
test('start lost response reuses exact authorization state',()=>assert.equal(startReplayDecision(t),'same_authorize_url'));
test('same key changed payload is conflict',()=>assert.equal(startReplayDecision({...t,payloadHash:'b'.repeat(64)}),'idempotency_conflict'));
test('expired state is never replayed',()=>assert.equal(startReplayDecision({...t,now:t.stateExpiresAt}),'restart_required'));
for(const status of ['oauth_returned','exchanging','saving','awaiting_account_confirmation']) test('start retry after '+status,()=>assert.equal(startReplayDecision({...t,status}),'resume_connecting'));
test('start replay completed is receipt resume',()=>assert.equal(startReplayDecision({...t,status:'completed'}),'resume_complete'));
for(const status of ['failed','cancelled','expired']) test('start replay terminal '+status,()=>assert.equal(startReplayDecision({...t,status}),'restart_required'));
test('unknown start status is not guessed',()=>assert.throws(()=>startReplayDecision({...t,status:'huh'})));
test('bad fingerprint fails closed',()=>assert.throws(()=>startReplayDecision({...t,payloadHash:'x'})));
const c={requestedAttemptId:a,activeAttemptId:a,expectedRevision:3,revision:3,status:'awaiting_account_confirmation'};
test('confirmation binds correct candidate revision',()=>assert.equal(confirmationMatches(c),true));
test('old tab cannot approve new attempt',()=>assert.equal(confirmationMatches({...c,activeAttemptId:b}),false));
test('stale candidate cannot be approved',()=>assert.equal(confirmationMatches({...c,revision:4}),false));
test('confirmation not accepted during exchange',()=>assert.equal(confirmationMatches({...c,status:'exchanging'}),false));
test('negative confirmation revision rejected',()=>assert.equal(confirmationMatches({...c,expectedRevision:-1,revision:-1}),false));
for(const status of ['exchanging','saving']) test('cannot cancel live worker '+status,()=>assert.equal(canReplaceAttempt(status),false));
test('explicit replacement pending allowed',()=>assert.equal(canReplaceAttempt('pending'),true));
const rev={expectedAttemptId:a,receivedAttemptId:a,currentRevision:3,receivedRevision:4,currentStatus:'processing',receivedStatus:'processing'};
test('monotonic same-attempt status accepted',()=>assert.equal(shouldAcceptStatus(rev),true));
test('older status ignored',()=>assert.equal(shouldAcceptStatus({...rev,receivedRevision:2}),false));
test('higher revision from other attempt ignored',()=>assert.equal(shouldAcceptStatus({...rev,receivedAttemptId:b}),false));
test('unsafe status revision ignored',()=>assert.equal(shouldAcceptStatus({...rev,receivedRevision:Number.MAX_SAFE_INTEGER+1}),false));
const old={id:a,startedAt:'2026-09-10T00:00:00Z'},fresh={id:b,startedAt:'2026-09-10T00:01:00Z'};
test('older authorization cannot overwrite newer token',()=>assert.equal(isOlderAttempt(old,fresh),true));
test('newer authorization accepted by order policy',()=>assert.equal(isOlderAttempt(fresh,old),false));
test('attempt order deterministic on equal time',()=>assert.equal(isOlderAttempt(old,{...old,id:b}),true));
test('no previous attempt not stale',()=>assert.equal(isOlderAttempt(old,null),false));
for(const n of ['00123456789','0000000000','+82012345678']) test('phone DB prefix parity '+n,()=>assert.equal(normalizeKoreanPhone(n),null));
for(const n of ['010-1234-5678','02-123-4567','+82 10 1234 5678']) test('normalized phone matches SQL constraint '+n,()=>assert.match(normalizeKoreanPhone(n),/^\+82[1-9][0-9]{7,9}$/));
