import test from 'node:test';
import assert from 'node:assert/strict';
import {isOlderAttempt,shouldAcceptStatus} from '../server-reference/attempt-policy.mjs';
const high='f1c9a751-283b-4e88-97cc-8229c74059d4';
const low='a071f1c9-f9db-498f-90c2-d8211ec26a99';
const older={id:high,startedAt:'2026-09-10T00:00:00.000001Z'};
const newer={id:low,startedAt:'2026-09-10T00:00:00.000999Z'};
const status={expectedAttemptId:low,receivedAttemptId:low,currentRevision:5,receivedRevision:6,currentStatus:'completed',receivedStatus:'processing'};
test('completed cannot regress to higher-revision processing',()=>assert.equal(shouldAcceptStatus(status),false));
test('completed cannot regress at same revision',()=>assert.equal(shouldAcceptStatus({...status,receivedRevision:5}),false));
test('completed replay remains visible',()=>assert.equal(shouldAcceptStatus({...status,receivedStatus:'completed'}),true));
test('status comparison rejects missing status fields',()=>assert.equal(shouldAcceptStatus({...status,currentStatus:undefined,receivedStatus:undefined}),false));
test('status comparison rejects unknown status',()=>assert.equal(shouldAcceptStatus({...status,currentStatus:'made_up'}),false));
test('processing can reach completed',()=>assert.equal(shouldAcceptStatus({...status,currentStatus:'processing',receivedStatus:'completed'}),true));
test('same millisecond: earlier microsecond is stale despite greater UUID',()=>assert.equal(isOlderAttempt(older,newer),true));
test('same millisecond: later microsecond is not stale despite lower UUID',()=>assert.equal(isOlderAttempt(newer,older),false));
test('equivalent timezone values use equal-instant UUID order',()=>assert.equal(isOlderAttempt({id:low,startedAt:'2026-09-10T09:00:00.000001+09:00'},older),true));
test('exact instant and UUID uppercase replay is not stale',()=>assert.equal(isOlderAttempt({...older,id:older.id.toUpperCase()},older),false));
test('same fractional value with trailing zeros is equal',()=>assert.equal(isOlderAttempt({id:low,startedAt:'2026-09-10T00:00:00.1Z'},{id:low,startedAt:'2026-09-10T00:00:00.100000+00:00'}),false));
test('precision beyond database contract is rejected not truncated',()=>assert.throws(()=>isOlderAttempt({...older,startedAt:'2026-09-10T00:00:00.0000001Z'},newer),/INVALID_ATTEMPT_ORDER/));
test('invalid calendar date rejected',()=>assert.throws(()=>isOlderAttempt({...older,startedAt:'2026-02-30T00:00:00Z'},newer),/INVALID_ATTEMPT_ORDER/));
test('invalid candidate rejected even without existing record',()=>assert.throws(()=>isOlderAttempt({id:'x',startedAt:'not a timestamp'},null),/INVALID_ATTEMPT_ORDER/));
test('timezone-free comparison rejected',()=>assert.throws(()=>isOlderAttempt({...older,startedAt:'2026-09-10T00:00:00'},newer),/INVALID_ATTEMPT_ORDER/));
test('invalid UTC offset rejected',()=>assert.throws(()=>isOlderAttempt({...older,startedAt:'2026-09-10T00:00:00+24:00'},newer),/INVALID_ATTEMPT_ORDER/));
